### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by jp112sdl** [tdewaha/arduino-pocsag#1]
Hi!

Very useful code, thanks a lot!

Do you have a wiring diagram or a photo, where to put VCC; GND and DATA OUT on the RF Board?
(The code works and sometimes it decodes Pocsag messages. Maybe the signal of data out is not really clean)

**Comment by Xernito** [comment]
@jp112sdl 

Do solve the problem? I use a Arduino Uno. The on Board LED (PIN13) won't be disabel.
Where can I Setup the BAUD?

**Comment by jp112sdl** [comment]
I found a wiring diagram [here](http://tfn.mine.nu/motorola.html)

**Comment by Xernito** [comment]
This wiring I have. I also created a PCB as Adapter.
I wired the RF to pin 3 to my Arduino Uno but nothing happed.

**Comment by jp112sdl** [comment]
In the setup()-code there is only the `disable_led();`-function called. 
The LED on Pin13 is never enabled by code, so it is strange that your LED on Pin13 is not disabled.
I am using an Arduino Pro mini and the code is working fine expect issue #2

**Comment by jp112sdl** [comment]
P.S.: Are you from Germany? The we could talk in german... Maybe in Facebook? You can find the link to my FB profile in my Github profile

**Comment by Xernito** [comment]
Ja bin ich ;-) der FB link geht leider nicht, habe auch kein FB - Account; Skype, ICQ, Discord?

**Comment by jp112sdl** [comment]
Weder noch :D Also ich kenne meine alte ICQ Nummer noch, aber habs nicht mehr installiert.
Telegram?

**Comment by Xernito** [comment]
Telegram, Threema alles da ;-)

**Comment by jp112sdl** [comment]
Perfekt. Dann Telegram. Schreib mich einfach an... @jp112sdl
